// data.jsx — Portfolio content. Edit values here.

const PORTFOLIO = {
  name: "Aaron Johal",
  tagline: "Senior PM building real AI products for personal and business use.",
  lastUpdated: "21 Jan 25",
  links: {
    linkedin: "https://www.linkedin.com/in/aaronjohal/",
    github: "https://github.com/aaronjohal",
    email: "mailto:hello@aaronjohal.com",
  },

  about: {
    blurb: [
      "I've been building digital products since 2014 — starting as an engineer, which is still how I think. I moved into product because I was more interested in which problems were worth solving than in how to solve them. That combination feels more relevant now than it ever has.",
    ],
    companies: ["BBC", "ASOS", "Ocado Group", "Yoto"],
    facts: [
      ["role", "Senior Product Manager"],
      ["focus", "AI · LLM tooling · workflow automation"],
      ["years_pm", 8],
      ["projects_shipped", 23],
      ["coffees_per_day", 3.5],
      ["currently", "building 3 things at once"],
    ],
  },

  // 8 projects. Each surfaces as a "file" in the tree + a tab.
  projects: [
    {
      id: "01_inbox_triage",
      category: "personal",
      file: "01_inbox_triage.py",
      title: "Inbox Triage Agent",
      tagline: "Reads my email like a chief of staff would.",
      status: "shipped",
      stack: ["GPT-4o", "Gmail API", "Python", "Cron"],
      role: "PM + builder",
      problem: "I was losing 90 minutes a day to email. Most of it didn't need me — it needed a decision and a draft reply.",
      approach: [
        "Wrote a one-page spec describing what a 'good triage' looks like for me, by category.",
        "Built a classifier that buckets mail into Reply, Read, Defer, Trash with reasoning.",
        "Layered on a draft-writer that mimics my voice from 18 months of sent mail.",
        "Daily 8am digest in Slack — one tap to send the drafts.",
      ],
      outcome: [
        "Time spent on email dropped ~63% over 4 weeks.",
        "Draft acceptance rate hovers around 71%.",
        "Stopped checking email between meetings entirely.",
      ],
      learned: "Most email isn't 'communication' — it's status updates that should have been a dashboard. The agent surfaced this much faster than any process change would have.",
      github: "https://github.com/aaronjohal/inbox-triage",
      visual: "terminal",
    },
    {
      id: "02_meeting_notes",
      category: "professional",
      file: "02_meeting_notes.ts",
      title: "Meeting Notes → Action Items",
      tagline: "Whisper + LLM that ships me a TODO before I leave the room.",
      status: "shipped",
      stack: ["Whisper", "Claude", "TypeScript", "Raycast"],
      role: "PM + builder",
      problem: "Notes were either too granular (transcript) or too vague (3 bullets). I wanted action items with owners and dates, attached to the actual quote.",
      approach: [
        "Captured audio locally via Raycast extension; transcribed with whisper.cpp.",
        "Designed an LLM pipeline: transcript → decisions → action items → owner inference.",
        "Added a 'why' field that links each action back to the moment in the call.",
      ],
      outcome: [
        "Used in 200+ meetings across 3 quarters.",
        "Adopted by my team after they saw the output once.",
        "Killed our 'notes-taker rotation' chore overnight.",
      ],
      learned: "Owner inference is the magic. Without it, you have a transcript with bullet points. With it, you have a meeting-ending artifact that ships.",
      github: "https://github.com/aaronjohal/meeting-notes",
      visual: "transcript",
    },
    {
      id: "03_spec_writer",
      category: "professional",
      file: "03_spec_writer.md",
      title: "Spec Writer Copilot",
      tagline: "From half-baked idea to v1 PRD in ~12 minutes.",
      status: "shipped",
      stack: ["Claude", "Next.js", "Vercel", "Linear API"],
      role: "PM + builder",
      problem: "Writing a PRD from a fuzzy thought was the slowest, lowest-leverage part of my week. The bottleneck was 'getting unstuck,' not writing.",
      approach: [
        "Designed a structured interview flow: problem → users → constraints → success.",
        "Each answer streams into a living spec on the right.",
        "Final pass surfaces missing sections with a 'PM smell' check (vague metrics, missing edge cases, etc.).",
      ],
      outcome: [
        "Used by ~40 PMs at my company.",
        "Median PRD time-to-first-draft: 47 min → 12 min.",
        "Promoted to internal tool.",
      ],
      learned: "PMs don't want a spec generator — they want a thinking partner that won't let them be lazy. The 'smell' check did more for quality than the generator did for speed.",
      github: "https://github.com/aaronjohal/spec-writer",
      visual: "spec",
    },
    {
      id: "04_dad_jokes",
      category: "personal",
      file: "04_dad_jokes.js",
      title: "Personalized Dad-Joke API for my Kids",
      tagline: "A side quest. Surprisingly hard. Surprisingly worth it.",
      status: "shipped",
      stack: ["GPT-4o-mini", "Cloudflare Workers", "iMessage shortcut"],
      role: "PM + dad",
      problem: "My 7yo loves dad jokes. I had run out. The internet's repository is — surprisingly — bad.",
      approach: [
        "Fine-tuned a small model on a curated set of 600 'actually good for a 7yo' jokes.",
        "Built an iMessage shortcut: he texts 'joke' to a number and gets one.",
        "Added a 'rate this joke' loop that quietly improves the model.",
      ],
      outcome: [
        "1,400+ jokes delivered.",
        "Average rating climbed from 2.8 → 4.1.",
        "Daughter (4) now also uses it. Demands knock-knock jokes only.",
      ],
      learned: "Building for a real, demanding user-of-one teaches more than any sprint planning. He didn't care about the architecture; he cared whether the joke landed.",
      github: "https://github.com/aaronjohal/dad-jokes",
      visual: "imessage",
    },
    {
      id: "05_research_synth",
      category: "professional",
      file: "05_research_synth.py",
      title: "Customer Research Synthesizer",
      tagline: "30 interviews → patterns → quotes → themes — in an afternoon.",
      status: "shipped",
      stack: ["Claude", "Pinecone", "Streamlit"],
      role: "PM + builder",
      problem: "Synthesizing 30 customer interviews used to take me a full week. Half of that week was just remembering which person said what.",
      approach: [
        "Each transcript is chunked, embedded, and tagged with persona + context.",
        "An LLM pass extracts claims with confidence + source quotes.",
        "Theme clustering with manual override — the PM stays in the loop.",
      ],
      outcome: [
        "Synthesis time: 5 days → 4 hours.",
        "Adopted by 2 sister product teams.",
        "We started doing more interviews because the cost dropped.",
      ],
      learned: "The model is good at extraction, terrible at judgment. Keep PMs in the theming step. The leverage compounds when synthesis stops being the bottleneck — you do more research, not less.",
      github: "https://github.com/aaronjohal/research-synth",
      visual: "themes",
    },
    {
      id: "06_changelog_bot",
      category: "professional",
      file: "06_changelog_bot.go",
      title: "Auto-Changelog from Commits",
      tagline: "Engineering ships, customers hear about it.",
      status: "shipped",
      stack: ["Go", "GitHub Webhooks", "Claude", "Notion API"],
      role: "PM + builder",
      problem: "We shipped a lot, but external changelog updates lagged by weeks. Engineers hated writing them; I hated chasing.",
      approach: [
        "Listen to merged PRs on main.",
        "Group by feature using semantic clustering.",
        "Draft a customer-facing entry per cluster, in our voice. Route to me for sign-off.",
      ],
      outcome: [
        "Changelog cadence: 'whenever' → weekly, automatically.",
        "Engineering complaints about changelog work: → 0.",
      ],
      learned: "The hard part wasn't generation — it was tone. Took 6 prompt iterations to stop sounding like a robot reading a release notes file. Voice is a product surface.",
      github: "https://github.com/aaronjohal/changelog-bot",
      visual: "changelog",
    },
    {
      id: "07_familygpt",
      category: "personal",
      file: "07_familygpt.tsx",
      title: "FamilyGPT (Recipes, Schedules, Sanity)",
      tagline: "A household assistant my wife actually uses. The bar.",
      status: "in_progress",
      stack: ["Claude", "Supabase", "React Native"],
      role: "PM + builder + spouse",
      problem: "Our shared cognitive load (meals, kid schedules, vet appointments) lived in 4 apps and 1 spouse's head. The spouse was getting tired.",
      approach: [
        "Single chat surface that reads our shared calendar + recipe library + grocery state.",
        "Speaks in 'we' voice. Suggests, doesn't decide.",
        "Has memory — knows the kids' allergies, the dog's medication, what we already ate this week.",
      ],
      outcome: [
        "Wife uses it daily. (This is the metric.)",
        "Reduced my mental tax for meal-planning to roughly zero.",
        "Caught one missed dentist appointment. Worth the build.",
      ],
      learned: "Personal AI is harder than product AI. The bar for 'do not annoy me' is unforgiving. Trust takes weeks; one bad recommendation breaks it.",
      github: "https://github.com/aaronjohal/familygpt",
      visual: "chat",
    },
    {
      id: "08_pm_dashboard",
      category: "professional",
      file: "08_pm_dashboard.html",
      title: "PM Health Dashboard",
      tagline: "The metrics every PM should look at, in one place.",
      status: "in_progress",
      stack: ["Claude", "Mixpanel", "Linear", "Looker"],
      role: "PM + builder",
      problem: "I had 6 dashboards open every Monday. None of them told me the one thing I needed: is the product getting better, or am I just shipping stuff?",
      approach: [
        "Defined 5 health metrics (activation, retention, NPS, time-to-value, support load).",
        "LLM weekly summary: 'here's what changed, here's what to look at.'",
        "Anomaly detection — but with prose, not red squiggles.",
      ],
      outcome: [
        "Personal: 6 dashboards → 1.",
        "Beta: 4 PMs using it; one reported it 'changed how I run my Mondays.'",
      ],
      learned: "Dashboards don't lack data — they lack narrative. A weekly 2-paragraph summary with 3 callouts beat a dashboard with 27 charts. By a lot.",
      github: "https://github.com/aaronjohal/pm-dashboard",
      visual: "dashboard",
    },
  ],

  skills: {
    Discovery: ["User interviews", "Jobs-to-be-Done", "Survey design", "Diary studies"],
    Definition: ["PRDs that are read", "Opportunity sizing", "Strategy memos", "Pre-mortems"],
    Delivery: ["Sprint planning", "Roadmapping", "Async-first ops", "Risk burndowns"],
    Data: ["SQL", "Mixpanel / Amplitude", "Cohort analysis", "Causal inference (lite)"],
    AI_specific: ["Prompt engineering", "Eval design", "RAG architecture", "Model selection"],
    Building: ["Python", "TypeScript", "React", "Next.js", "Cursor", "Replit"],
    Design: ["Figma", "Wireframing", "Prototyping in code", "Design crits"],
    Comms: ["Exec narratives", "Customer letters", "Postmortems", "Town halls"],
  },

  process: [
    { step: "01", name: "Smell the problem", note: "Ten conversations before one slide." },
    { step: "02", name: "Write the press release", note: "If I can't write it, I don't understand it yet." },
    { step: "03", name: "Build the jankiest version", note: "If a 4-hour prototype works, I trust it more than a 4-week roadmap." },
    { step: "04", name: "Put it in front of one user", note: "One real user beats six imagined ones." },
    { step: "05", name: "Decide: kill, fix, ship", note: "Killing is a feature." },
    { step: "06", name: "Ship a small slice", note: "If it can't be shipped in two weeks, it's not a slice." },
    { step: "07", name: "Watch the data + the faces", note: "Numbers tell you what. Faces tell you why." },
    { step: "08", name: "Write down what I learned", note: "Public if I can. Private if I must." },
  ],

  reading: [
    { title: "Inspired", author: "Marty Cagan", note: "The basics. Re-read every 18 months." },
    { title: "The Hard Thing About Hard Things", author: "Ben Horowitz", note: "For the days that are hard." },
    { title: "Working Backwards", author: "Bryar & Carr", note: "Where I stole the press-release-first habit." },
    { title: "High Output Management", author: "Andy Grove", note: "The OG operating manual." },
    { title: "The Mom Test", author: "Rob Fitzpatrick", note: "If you only read one customer-research book." },
    { title: "Lenny's Newsletter", author: "Lenny Rachitsky", note: "Where I steal frameworks." },
    { title: "Stratechery", author: "Ben Thompson", note: "For thinking in systems." },
    { title: "Every", author: "Various", note: "AI-product writing, mostly." },
  ],
};

window.PORTFOLIO = PORTFOLIO;
